name: CD 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connects to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/imx-buy-bot
            git pull origin main
            rm -rf nodes_modules
            yarn
            pm2 start "yarn buy-usdc >> /home/nvcq/logs/buy-usdc.log"
            pm2 start "yarn buy-eth >> /home/nvcq/logs/buy-eth.log"
            pm2 start "yarn buy-imx >> /home/nvcq/logs/buy-imx.log"